export const SET_USER_ID = 'SET_USER_ID';

export const ADD_NODE_REQUEST = 'ADD_NODE_REQUEST';
export const ADD_NODE_SUCCESS = 'ADD_NODE_SUCCESS';
export const ADD_NODE_FAILURE = 'ADD_NODE_FAILURE';

export const DELETE_NODE_REQUEST = 'DELETE_NODE_REQUEST';
export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS';
export const DELETE_NODE_FAILURE = 'DELETE_NODE_FAILURE';

export const UPDATE_NODE_REQUEST = 'UPDATE_NODE_REQUEST';
export const UPDATE_NODE_SUCCESS = 'UPDATE_NODE_SUCCESS';
export const UPDATE_NODE_FAILURE = 'UPDATE_NODE_FAILURE';

export const GET_NODES_REQUEST = 'GET_NODES_REQUEST';
export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS';
export const GET_NODES_FAILURE = 'GET_NODES_FAILURE';

export const GET_ACTIVE_NODE_REQUEST = 'GET_ACTIVE_NODE_REQUEST';
export const GET_ACTIVE_NODE_SUCCESS = 'GET_ACTIVE_NODE_SUCCESS';
export const GET_ACTIVE_NODE_FAILURE = 'GET_ACTIVE_NODE_FAILURE';